# Generated by Django 4.1.7 on 2023-03-16 22:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_postpagegamecategory_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpagegamecategory",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="main.gamepage",
            ),
        ),
    ]
