# Generated by Django 4.1.7 on 2023-03-17 08:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_postpagegamecategory_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductListPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductList",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "main.basepage",
            ),
        ),
    ]
