# Generated by Django 4.1.7 on 2023-03-20 16:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_cardspage_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateField(verbose_name="Post date")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "text_and_buttons",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.TextBlock()),
                                        (
                                            "buttons",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "button_text",
                                                            wagtail.blocks.CharBlock(
                                                                label="Text",
                                                                max_length=50,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "button_link",
                                                            wagtail.blocks.CharBlock(
                                                                label="Link",
                                                                max_length=255,
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "mainbutton",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "button_text",
                                                        wagtail.blocks.CharBlock(
                                                            label="Text",
                                                            max_length=50,
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "button_link",
                                                        wagtail.blocks.CharBlock(
                                                            label="Link",
                                                            max_length=255,
                                                            required=True,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
    ]
