# Generated by Django 4.1.7 on 2023-03-20 16:46

from django.db import migrations
import main.blocks.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_blogpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text_and_buttons",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    main.blocks.blocks.APIImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "credit_text",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "credit_link",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=None,
            ),
        ),
    ]
