# Generated by Django 4.1.7 on 2023-03-20 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_blogpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="date",
        ),
    ]
